name = input ("Hey there, what's your name?").strip().title()
print ("Ooh, that's a nice nice name!")
hobby = input ("So, what do you like to do" +name).strip().title()
print = input ("I've heard of" +hobby)
place = input ("I was gonna try it out, where should i go to do that?")
print = input ("Okay, I'll go, but only if you come with alright?")
print = input ("Okay")
directions = input ("How do I get there?").sstrip().title()
print = input ("See you there" +name)
print = input ("And just to clarify," +directions)
print = input ("Bye!!")
