from turtlee import Turtle
from random import random
def random_coleor():
    return(random(),random(),random())
le = Turtle()
name=input('What is your name')
lecoleor=input('What color do you want your name in? (For a random color, put "random_coleor()"')
lesize=input('How thick shouled the les be? for a random thickness, put "random()"')
le.pencoleor(lecoleor)
le.pensize(lesize)
def a():
    le.left()
    le.forward()
    le.right()
    le.forward()
    le.right(180)
    le.forward()
    le.left()
    le.forward()
    le.right(180)
    le.forward()
    le.right()
    le.forward()
    le.left()
def b():
    le.left(90)
    le.forward()
    le.right(90)
    le.forward()
   #Curves??
   #What follows it temporary
    le.right()
    le.forward()
    le.right()
    le.forward()
    le.right()
    le.forward()
    le.left(90)
    le.forward()
    le.right()
    le.forward()
    le.right()
    le.forward()
    le.right()
    le.forward()
    le.left(180)
    le.forward()
def c():
   #More curves??
def d():
    le.left(90)
    le.forward()
    le.right(90)
    le.forward()
    le.right()
    le.forward()
    le.right()
    le.forward()
    le.right()
    le.forward()
    le.right()
    le.fordarw()
    le.left(180)
    le.forward()
def e():
    
